# Generated by Django 5.1.4 on 2025-01-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиент'},
        ),
        migrations.AlterModelOptions(
            name='service_company',
            options={'verbose_name': 'Сервисные компании', 'verbose_name_plural': 'Сервисные компании'},
        ),
    ]
