# Generated by Django 5.1.4 on 2025-01-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='basecompany',
            name='сategory',
            field=models.CharField(choices=[('Клиент', 'Клиент'), ('Сервисная организация', 'Сервисная организация'), ('Менеджер', 'Менеджер')], default='Клиент', max_length=21),
        ),
    ]
