# Generated by Django 5.1.4 on 2025-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_client_options_basecompany_сategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecompany',
            name='сategory',
            field=models.CharField(choices=[('Клиент', 'Клиент'), ('Сервисные компании', 'Сервисные компании'), ('Менеджер', 'Менеджер')], default='Клиент', max_length=21),
        ),
    ]
